"""velvet.ir — SolIR: variables, operations, conversion and SSA.

Original clean-room implementation (spec/architecture.md §6).
"""

from velvet.ir.convert import convert_function, convert_unit
from velvet.ir.operations import (
    Assignment,
    Binary,
    Condition,
    Delete,
    EventCall,
    HighLevelCall,
    Index,
    InitArray,
    InternalCall,
    InternalDynamicCall,
    LibraryCall,
    LowLevelCall,
    Member,
    NewArray,
    NewContract,
    NewElementaryType,
    NewStructure,
    Operation,
    OperationWithLValue,
    Phi,
    Push,
    Return,
    Send,
    SolidityCall,
    Transfer,
    TypeConversion,
    Unary,
    Unpack,
)
from velvet.ir.variables import (
    IRVariable,
    ReferenceVariable,
    TemporaryVariable,
    TupleVariable,
)

__all__ = [
    "IRVariable",
    "TemporaryVariable",
    "ReferenceVariable",
    "TupleVariable",
    "Operation",
    "OperationWithLValue",
    "Assignment",
    "Binary",
    "Unary",
    "Index",
    "Member",
    "NewArray",
    "NewContract",
    "NewStructure",
    "NewElementaryType",
    "Push",
    "Delete",
    "TypeConversion",
    "Unpack",
    "InitArray",
    "HighLevelCall",
    "LowLevelCall",
    "LibraryCall",
    "InternalCall",
    "InternalDynamicCall",
    "SolidityCall",
    "EventCall",
    "Send",
    "Transfer",
    "Return",
    "Condition",
    "Phi",
    "convert_function",
    "convert_unit",
]
